sudo: required
services:
  - docker

before_install:
  - docker build -t degeb/docker-k8s-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true degeb/docker-k8s-test npm test

after-success: 
  - docker build -t degeb/docker-k8s-client ./client
  - docker build -t degeb/docker-k8s-nginx ./nginx
  - docker build -t degeb/docker-k8s-server ./server
  - docker build -t degeb/docker-k8s-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push degeb/docker-k8s-client
  - docker push degeb/docker-k8s-nginx
  - docker push degeb/docker-k8s-server
  - docker push degeb/docker-k8s-worker