apiVersion: v1
kind: Service
metadata:
    name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector: # select client-deployment pods
    component: web
  ports:
    - port: 3000 # port to be accessed from other objects
      targetPort: 3000 # target port of pod