apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server # [key]: [value] both can be called anything but must match with templates
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: degeb/docker-k8s-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres # default user name (not best form to use this)
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432' # also set up in postgres cluster ip service (also pg default port)
            - name: PGDTABASE
              value: postgres # also default (not best practiec)
            - name: PGPASSWORD # name of env variable -> not related to secret
              valueFrom: 
                secretKeyRef:
                  name: pgpassword # name of secret where env is stored
                  key: PGPASSWORD # as in secret